/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ohjelmoinnin.harkka.syntetisaattori.gui;

import net.beadsproject.beads.data.Buffer;
import ohjelmoinnin.harkka.syntetisaattori.sovelluslogiikka.Oskillaattori;
import ohjelmoinnin.harkka.syntetisaattori.sovelluslogiikka.Syntetisaattorisovellus;

/**
 *
 * @author peltonpa
 */
public class Gui extends javax.swing.JPanel {

    /**
     * Creates new form Gui
     */
    private Syntetisaattorisovellus syna;

    public Gui(Syntetisaattorisovellus syna) {
        this.syna = syna;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabelOsc2 = new javax.swing.JLabel();
        jLabelOsc1 = new javax.swing.JLabel();
        jLabelOsc3 = new javax.swing.JLabel();
        osc2OnOff = new javax.swing.JToggleButton();
        osc1OnOff = new javax.swing.JToggleButton();
        osc3OnOff = new javax.swing.JToggleButton();
        Lopetusnappi = new javax.swing.JButton();
        Soittonappi = new javax.swing.JButton();
        osc1Sini = new javax.swing.JRadioButton();
        osc1Saha = new javax.swing.JRadioButton();
        osc1Kantti = new javax.swing.JRadioButton();
        osc1Kolmio = new javax.swing.JRadioButton();
        osc1Kohina = new javax.swing.JRadioButton();
        osc2Kantti = new javax.swing.JRadioButton();
        osc2Kolmio = new javax.swing.JRadioButton();
        osc2Kohina = new javax.swing.JRadioButton();
        osc2Sini = new javax.swing.JRadioButton();
        osc2Saha = new javax.swing.JRadioButton();
        osc3Saha = new javax.swing.JRadioButton();
        osc3Kolmio = new javax.swing.JRadioButton();
        osc3Kantti = new javax.swing.JRadioButton();
        osc3Kohina = new javax.swing.JRadioButton();
        osc3Sini = new javax.swing.JRadioButton();
        oktaavilabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");
        osc1Sini.setSelected(true);

        osc2Sini.setSelected(true);

        osc3Sini.setSelected(true);

        jLabelOsc2.setText("Osc2");

        jLabelOsc1.setText("Osc1");

        jLabelOsc3.setText("Osc3");

        osc2OnOff.setText("On/off");
        osc2OnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                osc2OnOffMouseClicked(evt);
            }
        });

        osc1OnOff.setText("On/off");
        osc1OnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                osc1OnOffMouseClicked(evt);
            }
        });

        osc3OnOff.setText("On/off");
        osc3OnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                osc3OnOffMouseClicked(evt);
            }
        });

        Lopetusnappi.setText("Lopetus");
        Lopetusnappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LopetusnappiActionPerformed(evt);
            }
        });

        Soittonappi.setText("Soita");
        Soittonappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoittonappiActionPerformed(evt);
            }
        });

        buttonGroup1.add(osc1Sini);
        osc1Sini.setText("SINI");
        osc1Sini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc1SiniActionPerformed(evt);
            }
        });

        buttonGroup1.add(osc1Saha);
        osc1Saha.setText("SAHA");
        osc1Saha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc1SahaActionPerformed(evt);
            }
        });

        buttonGroup1.add(osc1Kantti);
        osc1Kantti.setText("KANTTI");
        osc1Kantti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc1KanttiActionPerformed(evt);
            }
        });

        buttonGroup1.add(osc1Kolmio);
        osc1Kolmio.setText("KOLMIO");
        osc1Kolmio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc1KolmioActionPerformed(evt);
            }
        });

        buttonGroup1.add(osc1Kohina);
        osc1Kohina.setText("KOHINA");
        osc1Kohina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc1KohinaActionPerformed(evt);
            }
        });

        buttonGroup2.add(osc2Kantti);
        osc2Kantti.setText("KANTTI");
        osc2Kantti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc2KanttiActionPerformed(evt);
            }
        });

        buttonGroup2.add(osc2Kolmio);
        osc2Kolmio.setText("KOLMIO");
        osc2Kolmio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc2KolmioActionPerformed(evt);
            }
        });

        buttonGroup2.add(osc2Kohina);
        osc2Kohina.setText("KOHINA");
        osc2Kohina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc2KohinaActionPerformed(evt);
            }
        });

        buttonGroup2.add(osc2Sini);
        osc2Sini.setText("SINI");
        osc2Sini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc2SiniActionPerformed(evt);
            }
        });

        buttonGroup2.add(osc2Saha);
        osc2Saha.setText("SAHA");
        osc2Saha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc2SahaActionPerformed(evt);
            }
        });

        buttonGroup3.add(osc3Saha);
        osc3Saha.setText("SAHA");
        osc3Saha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc3SahaActionPerformed(evt);
            }
        });

        buttonGroup3.add(osc3Kolmio);
        osc3Kolmio.setText("KOLMIO");
        osc3Kolmio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc3KolmioActionPerformed(evt);
            }
        });

        buttonGroup3.add(osc3Kantti);
        osc3Kantti.setText("KANTTI");
        osc3Kantti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc3KanttiActionPerformed(evt);
            }
        });

        buttonGroup3.add(osc3Kohina);
        osc3Kohina.setText("KOHINA");
        osc3Kohina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc3KohinaActionPerformed(evt);
            }
        });

        buttonGroup3.add(osc3Sini);
        osc3Sini.setText("SINI");
        osc3Sini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osc3SiniActionPerformed(evt);
            }
        });

        oktaavilabel.setText("Oktaavi");

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Soittonappi)
                .addGap(58, 58, 58)
                .addComponent(Lopetusnappi)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oktaavilabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(osc1OnOff)
                                .addGap(58, 58, 58)
                                .addComponent(jLabelOsc2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(osc1Saha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(osc1Sini, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(osc1Kolmio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addComponent(osc1Kantti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(osc1Kohina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(osc2OnOff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(jLabelOsc3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(osc2Saha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(osc2Sini, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(osc2Kolmio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(osc2Kantti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(osc2Kohina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(osc3OnOff)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(osc3Saha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(osc3Sini, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(osc3Kolmio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(osc3Kantti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(osc3Kohina, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabelOsc1)
                    .addContainerGap(474, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(osc1OnOff)
                    .addComponent(jLabelOsc2)
                    .addComponent(osc2OnOff)
                    .addComponent(jLabelOsc3)
                    .addComponent(osc3OnOff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(osc1Saha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc1Sini, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc1Kolmio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc1Kantti, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc1Kohina, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(osc2Saha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc2Sini, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc2Kolmio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc2Kantti, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc2Kohina, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(osc3Saha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc3Sini, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc3Kolmio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc3Kantti, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(osc3Kohina, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oktaavilabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lopetusnappi)
                    .addComponent(Soittonappi))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabelOsc1)
                    .addContainerGap(319, Short.MAX_VALUE)))
        );

        osc3Sini.setSelected(true);
    }// </editor-fold>//GEN-END:initComponents

    private void LopetusnappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LopetusnappiActionPerformed
        System.exit(0);
    }//GEN-LAST:event_LopetusnappiActionPerformed

    private void osc1OnOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_osc1OnOffMouseClicked
        onOff(0);
    }//GEN-LAST:event_osc1OnOffMouseClicked

    private void osc2OnOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_osc2OnOffMouseClicked
        onOff(1);
    }//GEN-LAST:event_osc2OnOffMouseClicked

    private void osc3OnOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_osc3OnOffMouseClicked
        onOff(2);
    }//GEN-LAST:event_osc3OnOffMouseClicked

    private void SoittonappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoittonappiActionPerformed
        try {
            this.syna.soita();
        } catch (Exception e) {
            System.out.println("Soita-metodissa errori");
        }
    }//GEN-LAST:event_SoittonappiActionPerformed

    private void osc1SiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc1SiniActionPerformed
        this.syna.getOskillaattorit().get(0).asetaAaltomuoto(Buffer.SINE);
    }//GEN-LAST:event_osc1SiniActionPerformed

    private void osc1SahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc1SahaActionPerformed
        this.syna.getOskillaattorit().get(0).asetaAaltomuoto(Buffer.SAW);
    }//GEN-LAST:event_osc1SahaActionPerformed

    private void osc1KanttiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc1KanttiActionPerformed
        this.syna.getOskillaattorit().get(0).asetaAaltomuoto(Buffer.SQUARE);
    }//GEN-LAST:event_osc1KanttiActionPerformed

    private void osc1KolmioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc1KolmioActionPerformed
        this.syna.getOskillaattorit().get(0).asetaAaltomuoto(Buffer.TRIANGLE);
    }//GEN-LAST:event_osc1KolmioActionPerformed

    private void osc1KohinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc1KohinaActionPerformed
        this.syna.getOskillaattorit().get(0).asetaAaltomuoto(Buffer.NOISE);
    }//GEN-LAST:event_osc1KohinaActionPerformed

    private void osc2KanttiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc2KanttiActionPerformed
        this.syna.getOskillaattorit().get(1).asetaAaltomuoto(Buffer.SQUARE);
    }//GEN-LAST:event_osc2KanttiActionPerformed

    private void osc2KolmioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc2KolmioActionPerformed
        this.syna.getOskillaattorit().get(1).asetaAaltomuoto(Buffer.TRIANGLE);
    }//GEN-LAST:event_osc2KolmioActionPerformed

    private void osc2KohinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc2KohinaActionPerformed
        this.syna.getOskillaattorit().get(1).asetaAaltomuoto(Buffer.NOISE);
    }//GEN-LAST:event_osc2KohinaActionPerformed

    private void osc2SiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc2SiniActionPerformed
        this.syna.getOskillaattorit().get(1).asetaAaltomuoto(Buffer.SINE);
    }//GEN-LAST:event_osc2SiniActionPerformed

    private void osc2SahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc2SahaActionPerformed
        this.syna.getOskillaattorit().get(1).asetaAaltomuoto(Buffer.SAW);
    }//GEN-LAST:event_osc2SahaActionPerformed

    private void osc3SahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc3SahaActionPerformed
        this.syna.getOskillaattorit().get(2).asetaAaltomuoto(Buffer.SAW);
    }//GEN-LAST:event_osc3SahaActionPerformed

    private void osc3KolmioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc3KolmioActionPerformed
        this.syna.getOskillaattorit().get(2).asetaAaltomuoto(Buffer.TRIANGLE);
    }//GEN-LAST:event_osc3KolmioActionPerformed

    private void osc3KanttiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc3KanttiActionPerformed
        this.syna.getOskillaattorit().get(2).asetaAaltomuoto(Buffer.SQUARE);
    }//GEN-LAST:event_osc3KanttiActionPerformed

    private void osc3KohinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc3KohinaActionPerformed
        this.syna.getOskillaattorit().get(2).asetaAaltomuoto(Buffer.NOISE);
    }//GEN-LAST:event_osc3KohinaActionPerformed

    private void osc3SiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osc3SiniActionPerformed
        this.syna.getOskillaattorit().get(2).asetaAaltomuoto(Buffer.SINE);
    }//GEN-LAST:event_osc3SiniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void onOff(int numero) {
        Oskillaattori osc = this.syna.haeOskillaattoriIndeksillä(numero);
        osc.onOffKytkin();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lopetusnappi;
    private javax.swing.JButton Soittonappi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabelOsc1;
    private javax.swing.JLabel jLabelOsc2;
    private javax.swing.JLabel jLabelOsc3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel oktaavilabel;
    private javax.swing.JRadioButton osc1Kantti;
    private javax.swing.JRadioButton osc1Kohina;
    private javax.swing.JRadioButton osc1Kolmio;
    private javax.swing.JToggleButton osc1OnOff;
    private javax.swing.JRadioButton osc1Saha;
    private javax.swing.JRadioButton osc1Sini;
    private javax.swing.JRadioButton osc2Kantti;
    private javax.swing.JRadioButton osc2Kohina;
    private javax.swing.JRadioButton osc2Kolmio;
    private javax.swing.JToggleButton osc2OnOff;
    private javax.swing.JRadioButton osc2Saha;
    private javax.swing.JRadioButton osc2Sini;
    private javax.swing.JRadioButton osc3Kantti;
    private javax.swing.JRadioButton osc3Kohina;
    private javax.swing.JRadioButton osc3Kolmio;
    private javax.swing.JToggleButton osc3OnOff;
    private javax.swing.JRadioButton osc3Saha;
    private javax.swing.JRadioButton osc3Sini;
    // End of variables declaration//GEN-END:variables
}
